// Package tfgen generates Terraform HCL stubs for Vault entity clients that
// have no entity alias in the activity export. These stubs create a
// vault_identity_entity and a vault_identity_entity_alias for each such record.
package tfgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vault-csv-normalizer/internal/normalizer"
)

var petAdjectives = []string{
	"amber", "bold", "calm", "dark", "eager", "fair", "glad", "hardy",
	"ivory", "jolly", "keen", "lofty", "merry", "noble", "proud",
	"quiet", "rapid", "silver", "tawny", "vivid", "warm", "young",
}

var petNouns = []string{
	"bear", "crane", "deer", "eagle", "fox", "goose", "hawk", "ibis",
	"jay", "kite", "lark", "mole", "newt", "otter", "panda", "quail",
	"raven", "swift", "teal", "vole", "wren", "yak", "zebra",
}

// nextPetName picks the next unused (adj_noun) name, cycling through all
// combinations. Falls back to "entity_N" if all 500+ combinations are used.
func nextPetName(used map[string]struct{}, counter *int) string {
	total := len(petAdjectives) * len(petNouns)
	for i := 0; i < total; i++ {
		idx := (*counter + i) % total
		name := petAdjectives[idx/len(petNouns)] + "_" + petNouns[idx%len(petNouns)]
		if _, ok := used[name]; !ok {
			*counter = (idx + 1) % total
			used[name] = struct{}{}
			return name
		}
	}
	*counter++
	name := fmt.Sprintf("entity_%d", *counter)
	used[name] = struct{}{}
	return name
}

// sanitizeID converts a string to a valid Terraform identifier by lowercasing
// and replacing non-alphanumeric characters with underscores.
func sanitizeID(s string) string {
	var b strings.Builder
	for _, ch := range strings.ToLower(s) {
		if (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') {
			b.WriteRune(ch)
		} else {
			b.WriteByte('_')
		}
	}
	result := b.String()
	for strings.Contains(result, "__") {
		result = strings.ReplaceAll(result, "__", "_")
	}
	return strings.Trim(result, "_")
}

func buildMethodGroupMap(groups [][]string) map[string]string {
	m := make(map[string]string)
	for _, g := range groups {
		if len(g) == 0 {
			continue
		}
		canonical := g[0]
		for _, method := range g {
			m[method] = canonical
		}
	}
	return m
}

// GenerateTF scans records for method-group members that have a non-empty
// mount_accessor but a blank entity_alias_name. These clients exist in Vault
// without an entity alias and need one created. For each such record a
// vault_identity_entity and vault_identity_entity_alias stub is written to
// outputPath. Mount accessors are emitted as Terraform variables so the caller
// can override them per environment. Returns the number of stubs written.
func GenerateTF(records []normalizer.Record, groups [][]string, outputPath string) (int, error) {
	groupMap := buildMethodGroupMap(groups)

	var targets []normalizer.Record
	for _, r := range records {
		if r.EntityAliasName != "" {
			continue // already aliased — skip
		}
		if r.MountAccessor == "" {
			continue // no mount accessor — cannot create alias
		}
		if normalizer.IsPKIClient(r) {
			continue // PKI clients are excluded from alias management
		}
		mt := r.MountType
		if mt == "" {
			mt = r.AuthMethod
		}
		if _, ok := groupMap[mt]; !ok {
			continue // not in any configured method group
		}
		targets = append(targets, r)
	}

	if len(targets) == 0 {
		return 0, nil
	}

	type mountInfo struct {
		accessor  string
		mountPath string
		mountType string
		varName   string
	}

	accessorSeen := make(map[string]*mountInfo)
	var accessorOrder []string
	for _, r := range targets {
		if _, ok := accessorSeen[r.MountAccessor]; !ok {
			mi := &mountInfo{
				accessor:  r.MountAccessor,
				mountPath: r.MountPath,
				mountType: r.MountType,
				varName:   "accessor_" + sanitizeID(r.MountAccessor),
			}
			accessorSeen[r.MountAccessor] = mi
			accessorOrder = append(accessorOrder, r.MountAccessor)
		}
	}

	var sb strings.Builder

	sb.WriteString("# Generated by vault-csv-normalizer\n")
	sb.WriteString("# These stubs represent entity clients with no alias in the Vault export.\n")
	sb.WriteString("# Fill in the TODO values and verify entity names before applying.\n\n")

	for _, acc := range accessorOrder {
		mi := accessorSeen[acc]
		desc := mi.mountPath
		if mi.mountType != "" {
			desc += " (" + mi.mountType + ")"
		}
		sb.WriteString(fmt.Sprintf("variable %q {\n", mi.varName))
		sb.WriteString(fmt.Sprintf("  description = %q\n", "Mount accessor for "+strings.TrimSpace(desc)))
		sb.WriteString("  type        = string\n")
		sb.WriteString(fmt.Sprintf("  default     = %q\n", mi.accessor))
		sb.WriteString("}\n\n")
	}

	used := make(map[string]struct{})
	counter := 0

	for _, r := range targets {
		name := nextPetName(used, &counter)
		mi := accessorSeen[r.MountAccessor]

		sb.WriteString(fmt.Sprintf("# client_id: %s | source: %s | mount: %s\n",
			r.ClientID, filepath.Base(r.Source), r.MountPath))

		sb.WriteString(fmt.Sprintf("resource \"vault_identity_entity\" %q {\n", name))
		entityName := r.EntityName
		if entityName == "" {
			entityName = "TODO"
		}
		sb.WriteString(fmt.Sprintf("  name = %q\n", entityName))
		sb.WriteString("}\n\n")

		sb.WriteString(fmt.Sprintf("resource \"vault_identity_entity_alias\" %q {\n", name))
		sb.WriteString("  name           = \"TODO\" # alias identifier used by the auth method\n")
		sb.WriteString(fmt.Sprintf("  mount_accessor = var.%s\n", mi.varName))
		sb.WriteString(fmt.Sprintf("  canonical_id   = vault_identity_entity.%s.id\n", name))
		sb.WriteString("}\n\n")
	}

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return 0, fmt.Errorf("writing %s: %w", outputPath, err)
	}
	return len(targets), nil
}
