// Package tfgen generates Terraform HCL to consolidate per-auth-method Vault
// client records into a single entity with multiple aliases. Each duplicate
// group found by --dedup-methods-per-file becomes one vault_identity_entity
// and one vault_identity_entity_alias per auth method in that group.
package tfgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vault-csv-normalizer/internal/normalizer"
)

var petAdjectives = []string{
	"amber", "bold", "calm", "dark", "eager", "fair", "glad", "hardy",
	"ivory", "jolly", "keen", "lofty", "merry", "noble", "proud",
	"quiet", "rapid", "silver", "tawny", "vivid", "warm", "young",
}

var petNouns = []string{
	"bear", "crane", "deer", "eagle", "fox", "goose", "hawk", "ibis",
	"jay", "kite", "lark", "mole", "newt", "otter", "panda", "quail",
	"raven", "swift", "teal", "vole", "wren", "yak", "zebra",
}

// nextPetName picks the next unused adj_noun name from the wordlists.
func nextPetName(used map[string]struct{}, counter *int) string {
	total := len(petAdjectives) * len(petNouns)
	for i := 0; i < total; i++ {
		idx := (*counter + i) % total
		name := petAdjectives[idx/len(petNouns)] + "_" + petNouns[idx%len(petNouns)]
		if _, ok := used[name]; !ok {
			*counter = (idx + 1) % total
			used[name] = struct{}{}
			return name
		}
	}
	*counter++
	name := fmt.Sprintf("entity_%d", *counter)
	used[name] = struct{}{}
	return name
}

// sanitizeID converts a string to a valid Terraform identifier.
func sanitizeID(s string) string {
	var b strings.Builder
	for _, ch := range strings.ToLower(s) {
		if (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') {
			b.WriteRune(ch)
		} else {
			b.WriteByte('_')
		}
	}
	result := b.String()
	for strings.Contains(result, "__") {
		result = strings.ReplaceAll(result, "__", "_")
	}
	return strings.Trim(result, "_")
}

// effectiveAlias returns the human-readable alias for a record. For OIDC,
// entity_alias_metadata_username holds the username; entity_alias_name may be
// a subject identifier that doesn't match other methods.
func effectiveAlias(r normalizer.Record) string {
	if (r.MountType == "oidc" || r.AuthMethod == "oidc") && r.EntityAliasMetadataUsername != "" {
		return r.EntityAliasMetadataUsername
	}
	return r.EntityAliasName
}

// GenerateTF writes Terraform HCL to outputPath for each alias duplicate group.
// groups is the output of normalizer.FindAliasDuplicatesForMethodsPerFile — each
// inner slice is a set of records that represent the same person authenticated via
// different auth methods. For each group, one vault_identity_entity resource and
// one vault_identity_entity_alias per record are generated, consolidating the
// separate per-method client records into a single Vault entity.
// Returns the number of entity stubs written.
func GenerateTF(groups [][]normalizer.Record, outputPath string) (int, error) {
	if len(groups) == 0 {
		return 0, nil
	}

	type mountInfo struct {
		accessor  string
		mountPath string
		mountType string
		varName   string
	}

	// Collect unique mount accessors across all groups.
	accessorSeen := make(map[string]*mountInfo)
	var accessorOrder []string
	for _, group := range groups {
		for _, r := range group {
			if r.MountAccessor == "" || accessorSeen[r.MountAccessor] != nil {
				continue
			}
			mi := &mountInfo{
				accessor:  r.MountAccessor,
				mountPath: r.MountPath,
				mountType: r.MountType,
				varName:   "accessor_" + sanitizeID(r.MountAccessor),
			}
			accessorSeen[r.MountAccessor] = mi
			accessorOrder = append(accessorOrder, r.MountAccessor)
		}
	}

	var sb strings.Builder

	sb.WriteString("# Generated by vault-csv-normalizer\n")
	sb.WriteString("# Each entity block consolidates records that represent the same person\n")
	sb.WriteString("# authenticated via different auth methods within a single billing period.\n")
	sb.WriteString("# Verify names before applying.\n\n")

	for _, acc := range accessorOrder {
		mi := accessorSeen[acc]
		desc := mi.mountPath
		if mi.mountType != "" {
			desc += " (" + mi.mountType + ")"
		}
		sb.WriteString(fmt.Sprintf("variable %q {\n", mi.varName))
		sb.WriteString(fmt.Sprintf("  description = %q\n", "Mount accessor for "+strings.TrimSpace(desc)))
		sb.WriteString("  type        = string\n")
		sb.WriteString(fmt.Sprintf("  default     = %q\n", mi.accessor))
		sb.WriteString("}\n\n")
	}

	// Group duplicate groups by source file, preserving order of first appearance.
	var fileOrder []string
	byFile := make(map[string][][]normalizer.Record)
	for _, group := range groups {
		source := filepath.Base(group[0].Source)
		if _, ok := byFile[source]; !ok {
			fileOrder = append(fileOrder, source)
		}
		byFile[source] = append(byFile[source], group)
	}

	used := make(map[string]struct{})
	counter := 0

	for _, source := range fileOrder {
		fileGroups := byFile[source]
		divider := strings.Repeat("#", 60)
		sb.WriteString(fmt.Sprintf("%s\n# Source: %s (%d alias group(s))\n%s\n\n",
			divider, source, len(fileGroups), divider))

		for _, group := range fileGroups {
			r0 := group[0]
			entityName := normalizer.BaseAlias(effectiveAlias(r0))

			methods := make([]string, 0, len(group))
			for _, r := range group {
				mt := r.MountType
				if mt == "" {
					mt = r.AuthMethod
				}
				methods = append(methods, mt)
			}

			petname := nextPetName(used, &counter)

			sb.WriteString(fmt.Sprintf("# alias: %s | methods: %s\n",
				entityName, strings.Join(methods, ", ")))

			sb.WriteString(fmt.Sprintf("resource \"vault_identity_entity\" %q {\n", petname))
			sb.WriteString(fmt.Sprintf("  name = %q\n", entityName))
			sb.WriteString("}\n\n")

			for i, r := range group {
				mt := r.MountType
				if mt == "" {
					mt = r.AuthMethod
				}
				aliasName := r.EntityAliasName
				if aliasName == "" {
					aliasName = "TODO"
				}
				aliasResource := fmt.Sprintf("%s_%d", petname, i)

				sb.WriteString(fmt.Sprintf("resource \"vault_identity_entity_alias\" %q {\n", aliasResource))
				sb.WriteString(fmt.Sprintf("  name           = %q # %s\n", aliasName, mt))
				if mi := accessorSeen[r.MountAccessor]; mi != nil {
					sb.WriteString(fmt.Sprintf("  mount_accessor = var.%s\n", mi.varName))
				} else {
					sb.WriteString("  mount_accessor = \"TODO\" # mount_accessor not in export\n")
				}
				sb.WriteString(fmt.Sprintf("  canonical_id   = vault_identity_entity.%s.id\n", petname))
				sb.WriteString("}\n\n")
			}
		}
	}

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return 0, fmt.Errorf("writing %s: %w", outputPath, err)
	}
	return len(groups), nil
}
